feat: RUST_REGEX supports more messages
mcb-dev/mCodingBot pull request #29
Opened 2022-08-24 16:44 UTC by qexat

:rocket: :fire: :stars:

2022-08-24 16:49 UTC, Lunarmagpie requested changes
Should use a word boundary instead of a space for `blazingly fast` imo

2022-08-24 16:50 UTC, qexat commented
> Should use a word boundary instead of a space for `blazingly fast` imo

how so? it is already using `\b`...?

2022-08-24 16:50 UTC, qexat commented
do you mean `\s`?

2022-08-24 16:51 UTC, Lunarmagpie commented
> 
> how so? it is already using `\b`.

Like `\bblazingly\bfast\b`

2022-08-24 16:52 UTC, CircuitSacul commented
> how so? it is already using \b...?

I think lunar means in between the words (e.x blazingly\bfast)

2022-08-24 16:53 UTC, qexat commented
> > how so? it is already using `\b`.
> 
> Like `\bblazingly\bfast\b`

that's kinda weird to me tbh, like any word boundary between blazingly and fast? :thinking:

2022-08-24 16:53 UTC, qexat commented
i'll change it anyway

2022-08-24 17:08 UTC, Lunarmagpie approved these changes

2022-08-24 17:24 UTC, MithicSpirit commented
Pretty sure that `\b` doesn't actually match any characters and only boundaries between characters, so now this doesn't match anything.

2022-08-24 17:41 UTC, MithicSpirit commented
imo undo that change. just leave it as a space. If you really want to match different types of spaces you could match on space, nbsp, zwsp, tab, newline, underscore, hyphen, etc.

2022-08-25 13:30 UTC, trag1c commented on mcodingbot/plugins/reactions.py
> +RUST_REGEX = re.compile(r"(\brust\b|\bblazingly fast\b)", flags=re.I)
```suggestion
RUST_REGEX = re.compile(r"(\brust\b|\bblazingly\s+fast\b)", flags=re.I)
```

2022-08-25 13:44 UTC, qexat commented
@Lunarmagpie @CircuitSacul can one of you approve to merge please?

2022-08-25 13:48 UTC, trag1c approved these changes

2022-08-25 13:54 UTC, merged