Highlight Cooldowns
mcb-dev/mCodingBot pull request #86
Opened 2022-11-17 20:37 UTC by CircuitSacul

This makes a few changes to improve highlights
 - [ ] If a message contains multiple triggers, combine them into a single DM.
 - [ ] Have a cooldown of 30s per (highlight, user, channel)
 - [ ] If a user sends a message in a channel, don't send them any highlights for the next minute.

These are just my feel for how it should work. If you think it should be tweaked lmk.

2022-11-17 21:12 UTC, MithicSpirit commented
These changes sound good to me, though please make the two cooldowns relatively easy to configure (like `MAX_HIGHLIGHTS` and `MAX_HIGHLIGHT_LENGTH`).

Might be interesting for us to look into having a proper config file for these things in the future (maybe we can commandeer the `config.json` for these purposes?).

2022-11-17 21:19 UTC, CircuitSacul commented
> These changes sound good to me, though please make the two cooldowns relatively easy to configure (like `MAX_HIGHLIGHTS` and `MAX_HIGHLIGHT_LENGTH`).
> 
> Might be interesting for us to look into having a proper config file for these things in the future (maybe we can commandeer the `config.json` for these purposes?).

Well these things would undoubtedly be defined in config.json (with defaults in config.py). Unless you meant per-user configuration? I think that's possible too.

2022-11-17 23:40 UTC, Lunarmagpie commented
> Well these things would undoubtedly be defined in config.json (with defaults in config.py). Unless you meant per-user configuration? I think that's possible too.

I think moving all config options to `config.py` would be a good idea. May open a PR for that before this one gets merged.

2022-11-17 23:43 UTC, MithicSpirit commented
> Well these things would undoubtedly be defined in config.json (with defaults in config.py). Unless you meant per-user configuration? I think that's possible too.

`MAX_HIGHLIGHTS` and `MAX_HIGHLIGHT_LENGTH` aren't in `config.json` :p. As for per-user configuration, it would be nice but probably overkill for now.

2022-11-18 00:01 UTC, CircuitSacul commented
> `MAX_HIGHLIGHTS` and `MAX_HIGHLIGHT_LENGTH` aren't in `config.json` :p. As for per-user configuration, it would be nice but probably overkill for now.

Oh oof. They should've been. Well, I'll be putting these settings in config. And yeah, per-user config is outside the scope of this pr anyways

2022-11-18 00:20 UTC, CircuitSacul commented
This is done. Ready for review.

2022-11-18 00:58 UTC, Lunarmagpie requested changes
I think switching to `NamedTuple` for buckets would help reduce mistakes when editing this code in the future.

2022-11-18 00:58 UTC, Lunarmagpie commented on mcodingbot/plugins/highlights.py
> +        ):
I think the `!= 0` can be removed. It might fit on one line then.

2022-11-18 00:58 UTC, Lunarmagpie commented on mcodingbot/config.py
> +    message_sent_cooldown: tuple[float, float] = (1, 60)
I think it is confusing what the `message_sent_cooldown` is for
```suggestion
    highlight_message_sent_cooldown: tuple[float, float] = (1, 60)
```

2022-11-18 01:28 UTC, Lunarmagpie commented
Still would prefer if `NamedTuple` was used.

2022-11-18 01:52 UTC, Lunarmagpie approved these changes

2022-11-18 01:53 UTC, Lunarmagpie requested changes
Actually the bucket should probably be `SentMessageBucket` so its obvious what variable its used with

2022-11-18 01:53 UTC, CircuitSacul commented
> Actually the bucket should probably be `SentMessageBucket`

I just named it "UserChannelBucket" b/c that's what it is literally

2022-11-18 01:54 UTC, Lunarmagpie commented
> I just named it "UserChannelBucket" b/c that's what it is literally

No reason to explain the properties of the class. Makes more sense to name it so its clear where its being used.

2022-11-18 01:58 UTC, Lunarmagpie approved these changes

2022-11-18 04:02 UTC, trag1c approved these changes

2022-11-18 04:02 UTC, merged