Use floodgate for ratelimiting
mcb-dev/mCodingBot pull request #95
Opened 2022-12-05 00:40 UTC by Lunarmagpie

I tested it and im pretty confident it works

2022-12-05 01:01 UTC, Lunarmagpie commented
I think this is blocked until hikari is updated to the newest version

2022-12-05 01:29 UTC, FuexFollets commented
May I ask what the purpose is of using floodgate?

2022-12-05 02:24 UTC, CircuitSacul requested changes

2022-12-05 02:24 UTC, CircuitSacul commented on mcodingbot/plugins/highlights.py
> +        if sent_message_cooldown.trigger(
This should be .retry_after

2022-12-06 03:23 UTC, Lunarmagpie commented
I merged this with upstream—CI passes so it should be reviewed

2022-12-06 17:14 UTC, CircuitSacul requested changes

2022-12-06 17:14 UTC, CircuitSacul commented on mcodingbot/plugins/highlights.py
> +        if sent_message_cooldown.trigger(
This should be .retry_after, or `if not sent_message_cooldown.can_trigger`. It shouldn't actually be triggering anything.

2022-12-06 17:14 UTC, CircuitSacul commented on mcodingbot/plugins/highlights.py
> +            retry_after = trigger_cooldown.retry_after(
This should be .trigger

2022-12-08 03:03 UTC, CircuitSacul approved these changes

2022-12-08 03:10 UTC, trag1c approved these changes

2022-12-08 03:10 UTC, merged